name: RPGEconomy
version: 1.0.0
main: io/github/ilongake/ribboneconomy/RibbonEconomy
api-version: '1.21.11'
authors:
  - ilongake
  - ocea-nio
description: RPG Economy Plugin

commands:

  money:
    description: 自分の所持金を確認します
    usage: /money

  pay:
    description: 他のプレイヤーにお金を送ります
    usage: /pay <プレイヤー> <金額>

  balancetop:
    description: 所持金ランキングを表示します
    usage: /balancetop

  job:
    description: 職業を管理します
    usage: /job

  exchange:
    description: 100円をエメラルド1個に交換します
    usage: /exchange

  quest:
    description: 依頼システム
    usage: /quest

  giveslot:
    description: スロットマシン看板を配布します
    usage: /giveslot [player]
    permission: slotmachine.give

  jobadmin:
    description: 職業を管理します
    usage: /jobadmin level <プレイヤー> <職業> <レベル>

  market:
    description: 農家マーケットを開きます
    usage: /market


permissions:

  slotmachine.give:
    description: スロットマシン看板を配布する権限
    default: op